SELECT * FROM LOB_CERRADO_DETALLE
WHERE 1=1
	AND InvtID = '99402'
	AND RefNbr = '034799'

	select * from LOB_IMPUESTOS
	where apdoc_id = 15785344
SELECT * FROM LOB_CERRADO WHERE cer_id IN (
1717755)


exec PA_ProcesoCarga_Lob_Impuestos_Por_Empresa '0102'
EXEC PA_ProcesoCarga_LobResumenDetalle '0102'
TRUNCATE TABLE LOB_RESUMEN_DETALLE
SELECT * FROM DOC_ARDOC WHERE 'EXENTO' IN (TaxId00,TaxID01,TaxId02)

SELECT A.Cer_Id 
	,B.DrAmt - B.CrAmt AS NETO
	,A.TaxAmt
	,(B.DrAmt - B.CrAmt) * 0.19 AS Imp
FROM LOB_CERRADO_DETALLE A
inner join LOB_CERRADO B ON A.Cer_Id = B.cer_id
WHERE A.TaxAmt IS NOT NULL AND A.TaxAmt != 0
--UPDATE LOB_CERRADO_DETALLE SET TaxAmt = NULL, TaxAmt_uf = NULL WHERE Emp_Cod = '0101'
SELECT * FROM DOC_APTran WHERE apdoc_id in (5470239) and User2 = 'IQ04'
SELECT * FROM LOB_CERRADO_DETALLE WHERE Cer_Id IN (2657961
,2633232
)
SELECT * FROM LOB_CERRADO WHERE Cer_Id IN (2633232
,2633231
)


SELECT * FROM LOB_CERRADO_DETALLE WHERE 15785344 in (Aux_apdoc_cl_id, Aux_apdoc_id)